### ISSUE TITLE
Obsolete features (to be removed?)

### ISSUE THREAD

**Issue by lmether** [PyCOMPLETE/PyHEADTAIL#110]
- field map module
 - libTPSA
 - trello, etc
 - Wideband feedback?

**Comment by aoeftiger** [comment]
Hey Lotta, 

- the `field_maps/field_map` module is used e.g. for frozen SC based on PIC. About `Transverse_Efield_map.py` I'm not sure -- I'm not using it, is it being used in the PyHT/PyECLOUD setup? If not then I think it's obsolete.
- `libTPSA` can be taken out, it was meant to provide another type of trackable data type (instead of number-based macro-particles) but we've never gone beyond basic tests. Anyway if this is ever taken into PyHEADTAIL, one would want to include a whole TPSA library (such as the one from MAD NG). Alongside with `libTPSA.py`, one can also remove `libintegrators.py` from `trackers`
- the trello has not been followed up, I also think we should remove the link here. What else falls under "etc"?
- wideband feedback -- let's check with @like2000 , I'm not sure?
- same goes for `cobra_functions/c_sin_cos.pyx` and `cobra_functions/interp_sin_cos.pyx`, not sure we need them -- @like2000 ?

**Comment by like2000** [comment]
* wideband feedback can go - that's now integral in Jani's modules.
* c_sin_cos.pyx adds dependencies on some C library without adding much benefit. Would remove as well.

**Comment by giadarol** [comment]
Hello, I confirm that field_maps/field_map is not used anywhere for cloud simulations

**Comment by lmether** [comment]
- Since the `field_maps/field_map.py` module is used at least for frozen SC with PIC and the `Transverse_Efield_map.py` by PyEC4PyHT, these are both staying for now.
 - The others, i.e. `libTPSA.py` + `libintegrators.py`,  `widebandfeedback.py` and `cobra_functions/c_sin_cos.pyx` and `cobra_functions/interp_sin_cos.pyx` will be removed in the next release.

**Comment by lmether** [comment]
Unused modules removed in [v1.16.0](https://github.com/PyCOMPLETE/PyHEADTAIL/releases/tag/v1.16.0)
